export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAILURE = 'PRODUCT_LIST_FAILURE'

export const PRODUCT_REPORT_REQUEST = 'PRODUCT_REPORT_REQUEST'
export const PRODUCT_REPORT_SUCCESS = 'PRODUCT_REPORT_SUCCESS'
export const PRODUCT_REPORT_FAILURE = 'PRODUCT_REPORT_FAILURE'